name: Linux

on:
  push:
    branches:
      - "master" 
      - "dev-ci" 
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  
  build-native:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ForeFire build
        run: sudo bash ./install-forefire.sh

      - name: Check version
        run: ./bin/forefire -v

      # - name: Test
      #   run: cd tests && bash run.bash


  docker:
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build -t forefire:latest .
      
      - name: Test Docker Image
        run: |
          # Run the container and check the version output
          docker run --rm forefire:latest forefire -v

      # - name: Run test inside Docker container
      #   run: docker run --rm forefire:latest sh ./test-forefire.sh